package com.example.ft.aidt; import android.content.Intent; import android.net.Uri; import android.os.Bundle; import android.support.annotation.NonNull; import android.support.design.widget.FloatingActionButton; import android.support.design.widget.Snackbar;
32
import android.view.View; import android.support.design.widget.NavigationView; import android.support.v4.view.GravityCompat; import android.support.v4.widget.DrawerLayout; import android.support.v7.app.ActionBarDrawerToggle; import android.support.v7.app.AppCompatActivity; import android.support.v7.widget.Toolbar; import android.view.Menu; import android.view.MenuItem; import android.widget.TextView; import android.widget.Toast; import com.google.android.gms.tasks.OnCompleteListener; import com.google.android.gms.tasks.Task; import com.google.firebase.auth.FirebaseAuth; import com.google.firebase.auth.FirebaseUser; public class Actual extends AppCompatActivity implements NavigationView.OnNavigationItemSelectedListener { private TextView lop; private FirebaseAuth auth; private FirebaseAuth.AuthStateListener authListener; @Override protected void onCreate(Bundle savedInstanceState) { super.onCreate(savedInstanceState); setContentView(R.layout.activity_actual); Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
33
setSupportActionBar(toolbar); auth = FirebaseAuth.getInstance(); final FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser(); authListener = new FirebaseAuth.AuthStateListener() { @Override public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) { FirebaseUser user = firebaseAuth.getCurrentUser(); if (user == null) { // user auth state is changed - user is null // launch login activity startActivity(new Intent(Actual.this, LoginActivity.class)); finish(); } } }; DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout); ActionBarDrawerToggle toggle = new ActionBarDrawerToggle( this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close); drawer.addDrawerListener(toggle); toggle.syncState(); NavigationView navigationView = (NavigationView)
34
findViewById(R.id.nav_view); navigationView.setNavigationItemSelectedListener(this); } @Override public void onBackPressed() { DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout); if (drawer.isDrawerOpen(GravityCompat.START)) { drawer.closeDrawer(GravityCompat.START); } else { super.onBackPressed(); } } @Override public boolean onCreateOptionsMenu(Menu menu) { // Inflate the menu; this adds items to the action bar if it is present. getMenuInflater().inflate(R.menu.actual, menu); return true; } @Override public boolean onOptionsItemSelected(MenuItem item) { // Handle action bar item clicks here. The action bar will // automatically handle clicks on the Home/Up button, so long // as you specify a parent activity in AndroidManifest.xml. int id = item.getItemId();
35
//noinspection SimplifiableIfStatement if (id == R.id.action_settings) { Intent i = new Intent(Actual.this,Settings.class); startActivity(i); } else if (id == R.id.chgf) { Intent i = new Intent(Actual.this,changepas.class); startActivity(i); } else if (id == R.id.Sigo) { auth.signOut(); startActivity(new Intent(Actual.this,MainActivity.class)); FirebaseAuth.AuthStateListener authListener = new FirebaseAuth.AuthStateListener() { @Override public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) { FirebaseUser user = firebaseAuth.getCurrentUser(); if (user == null) { startActivity(new Intent(Actual.this, LoginActivity.class)); finish(); } } }; } else if (id == R.id.del) { final FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
36
user.delete().addOnCompleteListener(new OnCompleteListener<Void>() { @Override public void onComplete(@NonNull Task<Void> task) { if(task.isSuccessful()) { Toast.makeText(Actual.this, "Account deleted", Toast.LENGTH_SHORT).show(); startActivity(new Intent(Actual.this,MainActivity.class)); } else { Toast.makeText(Actual.this,task.getException().getMessage(),Toast.LENGTH_LONG).show(); } } }); } else if (id == R.id.jki) { auth.signOut(); startActivity(new Intent(Actual.this,LoginActivity.class)); FirebaseAuth.AuthStateListener authListener = new FirebaseAuth.AuthStateListener() { @Override public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) { FirebaseUser user = firebaseAuth.getCurrentUser();
37
if (user == null) { startActivity(new Intent(Actual.this, LoginActivity.class)); finish(); } } }; } return super.onOptionsItemSelected(item); } @SuppressWarnings("StatementWithEmptyBody") @Override public boolean onNavigationItemSelected(MenuItem item) { // Handle navigation view item clicks here. int id = item.getItemId(); if (id == R.id.Setting) { Intent i = new Intent(Actual.this,Scheduler.class); startActivity(i); } else if (id == R.id.bmi) { Intent i = new Intent(Actual.this,bmi.class); startActivity(i); } else if (id == R.id.Baymax) { Intent i = new Intent(Actual.this,ai.class);
38
startActivity(i); } else if (id == R.id.Web) { Intent broom = new Intent(Intent.ACTION_VIEW,Uri.parse("https://bot.dialogflow.com/6faf85c8-d0bf-4e79-80f0-b8e6b696e62f \n")); startActivity(broom); } else if (id == R.id.abj) { Intent i = new Intent(Actual.this,about.class); startActivity(i); } else if(id == R.id.abjl) { startActivity(new Intent(Actual.this,Help.class)); } else if(id == R.id.Facebook) { Toast.makeText(getApplicationContext(),"After installing telegram search for 'Baymax_AIDT_Bot' in your app to access the bot",Toast.LENGTH_LONG).show(); startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://play.google.com/store/apps/details?id=org.telegram.messenger&hl=en_IN"))); } DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
39
drawer.closeDrawer(GravityCompat.START); return true; } }