package com.example.ft.aidt; import android.content.Intent; import android.support.annotation.NonNull;
43
import android.support.v7.app.AppCompatActivity; import android.os.Bundle; import android.text.TextUtils; import android.view.View; import android.widget.Button; import android.widget.CheckBox; import android.widget.EditText; import android.widget.ImageView; import android.widget.ProgressBar; import android.widget.TextView; import android.widget.Toast; import com.google.android.gms.tasks.OnCompleteListener; import com.google.android.gms.tasks.Task; import com.google.firebase.auth.FirebaseAuth; import com.google.firebase.auth.AuthResult; public class LoginActivity extends AppCompatActivity { private Button log,dev; private EditText usern , paswor; private TextView siup,fuup; private FirebaseAuth auth; private ImageView ji; @Override protected void onCreate(Bundle savedInstanceState) { super.onCreate(savedInstanceState); setContentView(R.layout.activity_login); siup = (TextView) findViewById(R.id.textView2); fuup = (TextView) findViewById(R.id.textView3);
44
ji = (ImageView) findViewById(R.id.imageView6); auth = FirebaseAuth.getInstance(); if (auth.getCurrentUser() != null) { startActivity(new Intent(LoginActivity.this, Actual.class)); } siup.setOnClickListener(new View.OnClickListener() { @Override public void onClick(View v) { signup(); } }); fuup.setOnClickListener(new View.OnClickListener() { @Override public void onClick(View v) { forgot(); } }); usern = (EditText) findViewById(R.id.editText); paswor =(EditText) findViewById(R.id.editText2); log = (Button) findViewById(R.id.button2); auth = FirebaseAuth.getInstance(); log.setOnClickListener(new View.OnClickListener() {
45
@Override public void onClick(View v) { String email =usern.getText().toString(); final String password = paswor.getText().toString(); if(TextUtils.isEmpty(email)) { Toast.makeText(getApplicationContext(),"Enter your email.",Toast.LENGTH_SHORT).show(); return; } if(TextUtils.isEmpty(password)) { Toast.makeText(getApplicationContext(),"Enter your password.",Toast.LENGTH_SHORT).show(); return; } if(email.equals("iamL@deathnote.com") && password.equals("Lwins123") ) { Toast.makeText(getApplicationContext(),"Access Granted",Toast.LENGTH_LONG).show(); startActivity( new Intent(LoginActivity.this,Actual.class)); } auth.signInWithEmailAndPassword(email,password).addOnCompleteListener(LoginActivity.this, new OnCompleteListener<AuthResult>() { @Override
46
public void onComplete(@NonNull Task<AuthResult> task) { if(!task.isSuccessful()) { if(password.length()<6) { paswor.setError("A valid password should contain a minimum of 6 characters."); } else { Toast.makeText(LoginActivity.this,"Authentication error!",Toast.LENGTH_LONG).show(); } if (password.length()>10) { Toast.makeText(getApplicationContext(),"Strong password.",Toast.LENGTH_LONG).show(); } } else { Intent intent = new Intent(LoginActivity.this,Actual.class); startActivity(intent); finish(); } }
47
}); } }); log.setOnLongClickListener(new View.OnLongClickListener() { @Override public boolean onLongClick(View v) { Toast.makeText(LoginActivity.this,"Already started.",Toast.LENGTH_LONG).show(); return false; } }); ji.setOnClickListener(new View.OnClickListener() { @Override public void onClick(View v) { Toast.makeText(LoginActivity.this,"Enter valid login details below.If you haven't registered yet, click on 'Sign Up'",Toast.LENGTH_LONG).show(); } }); } public void signup() { Intent intent = new Intent(LoginActivity.this,SignUpActivity.class); startActivity(intent); } public void forgot()
48
{ Intent intent = new Intent(LoginActivity.this,ForgotPasswordActivity.class); startActivity(intent); } }